/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:eceae3ad-6ac0-4b26-8bd4-37146d11c9d0",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_Elat4ojaD",
  aws_user_pools_web_client_id: "47aeucvmga6sdin5eoubqa25la",
  oauth: {},
};

export default awsConfig;
