/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:1c14fb01-663e-45b0-a5fd-26ad6e14b8cc",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_6EQc8UyWb",
  aws_user_pools_web_client_id: "5a83m8ke1049isihdnnuq2cn1o",
  oauth: {},
};

export default awsmobile;
